ingresses:
  argocd:
    hostname: argocd
    namespace: argocd
    service:
      name: argo-cd-argocd-server
      port: 80
  longhorn:
    hostname: longhorn
    namespace: longhorn-system
    service:
      name: longhorn-frontend
      port: 80
  vikunja:
    hostname: vikunja
    namespace: vikunja
    service:
      name: vikunja
      port: 80
  atoikura:
    hostname: atoikura
    namespace: atoikura
    service:
      name: atoikura
      port: 80
    backend:
      hostname: atoikura-api
      service:
        name: atoikura-api
        port: 8080
      
