backend:
  image: ghcr.io/utibori-jp/atoikura-backend:v0.4.0
  replicas: 1
  corsAllowedOrigin: "https://atoikura.tail078c12.ts.net"
  service:
    port: 8080
    targetPort: 8080

frontend:
  image: ghcr.io/utibori-jp/atoikura-frontend:v0.4.0
  replicas: 1
  service:
    port: 80
    targetPort: 80

postgres:
  image: postgres:18-alpine
  replicas: 1
  persistence:
    size: 1Gi
    storageClass: longhorn
