vikunja:
  image: vikunja/vikunja:latest
  replicas: 1
  service:
    port: 80
    targetPort: 3456
  persistence:
    size: 2Gi
    storageClass: longhorn
  publicUrl: "https://vikunja.tail078c12.ts.net"

postgres:
  image: postgres:16-alpine
  replicas: 1
  persistence:
    size: 2Gi
    storageClass: longhorn
  