apiVersion: v1
kind: Service
metadata:
  name: honeypot-jupyter
  namespace: honeypot-analytics
spec:
  selector:
    app: honeypot-jupyter
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8888
