apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: oci://ghcr.io/go-vikunja/helm-chart/vikunja
    targetRevision: 1.0.0
    helm:
      valuesObject:
        vikunja:
          ingress:
            main:
              enabled: false
          persistence:
            data:
              enabled: true
              accessMode: ReadWriteOnce
              size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
