# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  atoikura-api
  namespace: atoikura
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: atoikura-api
  template:
    metadata:
      labels:
        app: atoikura-api
    spec:
      containers:
        - name: atoikura-api
          image: {{ .Values.backend.image }}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: {{ .Values.backend.service.port | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: atoikura-secrets
                  key: DATABASE_URL
            - name: CORS_ALLOWED_ORIGIN
              value: {{ .Values.backend.corsAllowedOrigin | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: atoikura-secrets
                  key: JWT_SECRET
          ports:
            - containerPort: {{ .Values.backend.service.targetPort }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: atoikura-api
  namespace: atoikura
spec:
  type: ClusterIP
  selector:
    app: atoikura-api
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}

--- 
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  atoikura
  namespace: atoikura
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: atoikura
  template:
    metadata:
      labels:
        app: atoikura
    spec:   
      containers:
        - name: atoikura
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.service.targetPort }}
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: atoikura
  namespace: atoikura
spec:
  type: ClusterIP
  selector:
    app: atoikura
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
