apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-tailscale
  namespace: {{ .Values.ingresses.longhorn.namespace }}
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - {{ .Values.ingresses.longhorn.hostname }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingresses.longhorn.service.name }}
                port:
                  number: {{ .Values.ingresses.longhorn.service.port }}
